#!/bin/bash

if [ 0 -eq $# ]; then
  ./node_modules/.bin/mocha tests/[[:digit:]]_*.js
elif [ 1 -eq $# ]; then
  ./node_modules/.bin/mocha tests/$1_*.js
else
  ./node_modules/.bin/mocha tests/[[:digit:]]_*.js
fi 
